version: '3'
services:
  compass:
    image: "iotacafe/compass:coordinator-8306ac7"
    network_mode: host
    depends_on: 
      - 'iri'
    volumes: 
      - ./state:/state
      - ./layers:/layers
    command: coordinator_deploy.jar
      ${EXTRA_COMPASS_FLAGS}
      -broadcast
      -layers /layers
      -sigMode CURLP27
      -powMode CURLP81
      -mwm ${MWM}
      -security ${SECURITY_LEVEL}
      -seed MYSEEDHEREPLEASEREPLACEMEIMMEDIATELYWITHSOMETHINGSECURE99999999999999999999999999
      -tick ${TICK_RATE}
      -host http://localhost:${IRI_PORT}
      -statePath /state/statefile
  iri:
    network_mode: host
    image: "iotaledger/iri:latest"
    ports:
      - "${IRI_PORT}:${IRI_PORT}"
      - "5556:5556"
    volumes: 
      - ./config/snapshot.txt:/snapshot.txt
      - ./db:/iri/data
    command: >-
      --testnet true
      --remote true
      --zmq-enable-tcp true
      --remote-limit-api ""
      --testnet-coordinator ZRMNUUBQHVRFRFBOQZYGAUBSTJSHDVIPXHUDA9VAXFTDSGGRILPVMYLVOLVCIEHLFMQKUOHUIUWILCXGD
      --testnet-coordinator-security-level ${SECURITY_LEVEL}
      --testnet-coordinator-signature-mode CURLP27
      --mwm ${MWM}
      --milestone-start 0
      --milestone-keys 20
      --snapshot /snapshot.txt
      --max-depth 1000 
